services:
  db:
    image: postgres
    container_name: api_clients_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      - ./migrations/0001_create_table_clients.sql:/docker-entrypoint-initdb.d/0001_create_table_clients.sql
      - ./migrations/0002_add_primary_key_id.sql:/docker-entrypoint-initdb.d/0002_add_primary_key_id.sql
      - ./migrations/0003_create_index_email.sql:/docker-entrypoint-initdb.d/0003_create_index_email.sql

  server:
    container_name: api_clients_server
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
